### ISSUE TITLE
Problem with // comments in the last line

### ISSUE THREAD

**Issue by agershun** [lehni/uncomment.js#1]
If there is a // comment in the last line, it reduces last two characters of the last line:

``` js
    var res = uncomment("one\ntwo//three");
```

gives

```
    one
    t
```

**Comment by lehni** [comment]
Thanks for spotting, will look into it! Please note that it currently isn't very good at handling regular expressions also.

**Comment by agershun** [comment]
This is not problem of regular expression, but that you cut two last characters from the last line (you added them before as "__"), but in the last line you remove them as commented line.

**Comment by agershun** [comment]
I adapted the procedure to remove SQL /\* */ comments (see [here](https://github.com/agershun/alasql/blob/version-0.0.37/src/16comments.js)]. Also I use regexp to remove '//' comments later on the second pass:

```
    "//"(.*?)($|\r\n|\r|\n)
```

Thank you!

**Comment by lehni** [comment]
@agershun I have rewritten the algorithm to be faster and more memory efficient. You may want to update it too.

**Comment by agershun** [comment]
@lehni  :+1: I will review AlaSQL algorithms with you new version. Thank you!
